### ISSUE TITLE
build fail when under liferay-workspace/modules folder

### ISSUE THREAD

**Issue by AndyWu2015** [yasuflatland-lf/damascus#1]
Hey @yasuflatland-lf , you should not generate settings.gradle , build.gradle and gradlew files (cause they are nested projects) and remove all plugin applying, cause liferay workspace plugin will apply them.

**Comment by yasuflatland-lf** [comment]
Hi @AndyWu2015 

Thank you for testing this! I tested myself according to the following steps, but I could build and deploy properly. Please let me know more details of what you tried and environment as well.

My Environment
Blade version : 2.1.1.201705110328
Gradle version : Gradle 3.4.1
Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_112 (Oracle Corporation 25.112-b16)
OS:           Mac OS X 10.12.5 x86_64

Steps to reproduce:
1.  Create a folder, say test
2.  Go to test folder and run blade init --force to create Liferay workspace
3.  Go to modules folder
4.  Run damascus -init CompileTest -p com.liferay.test.compile -v 70
5.  Go to CompileTest folder
6.  Run damascus -create
7.  Run gradle build, the result is success
8.  Start up Liferay DXP de20 patched version
9.  Run blade deploy
10. Properly deployed
11. Login to Liferay as test@liferay.com user (Administrator)
12. The created portlet could be placed in a page.

**Comment by AndyWu2015** [comment]
yes , but when you cd to test root dir , and run "gradlew clean build" , it will fail.

**Comment by yasuflatland-lf** [comment]
Hi @AndyWu2015 

Oh, Ok, yeah I confirmed that. I'll fix that along with other bugs that I found!

**Comment by AndyWu2015** [comment]
IDE team are considering to integrate  your wonderful tool in to blade , so If I am free , I can help to fix bug and adding new features.

**Comment by yasuflatland-lf** [comment]
Hey @AndyWu2015, 

> IDE team are considering to integrate your wonderful tool in to blade , so If I am free , I can help to fix bug and adding new features.

That's what I couldn't ask for more! Liferay's improvement is pretty fast, so I was bit worried if I can keep this tool updated to the latest releases. In terms of this issue, I just tweaked code that's currently generated by Damascus. Is this what you mean? 

```https://github.com/yasuflatland-lf/for_confirm_damascus```

Navigate to ```${liferay_workspace_root}/modules/First``` and clone ```https://github.com/yasuflatland-lf/for_confirm_damascus``` underneath of the folder.

**Comment by AndyWu2015** [comment]
1. don't worry to much , we can help to update your tool.

2. yes , I can build success with following structure

![ws](https://user-images.githubusercontent.com/12250744/27266885-12248976-54d7-11e7-88d0-1d735d18e43b.png)

notice , there is no "for_confirm_damascus" folder

**Comment by yasuflatland-lf** [comment]
Hi, @AndyWu2015 it's fixed in dcb45ef75cfa9c43e99a76611e96a7770f1dca13 Thank you for your contribution!

**Comment by AndyWu2015** [comment]
thank you ! @yasuflatland-lf
