### ISSUE TITLE
Is it possible to release compatibility with Liferay Portal 7.3 ?

### ISSUE THREAD

**Issue by icarrara** [yasuflatland-lf/damascus#106]
I'm available for QA and tests as usual.

**Comment by yasuflatland-lf** [comment]
Hi @icarrara , I've just started 7.3 template development here 
https://github.com/yasuflatland-lf/sample-sb
I'll keep you updated.

**Comment by icarrara** [comment]
Hi @yasuflatland-lf , this is one of the best news I get in these dark months. 
Please let me know if I can contribute in any way according to my possibilities.

**Comment by yasuflatland-lf** [comment]
@icarrara 7.3 template has been released.

**Comment by icarrara** [comment]
@yasuflatland-lf , thank you very much. I'll start to generate some portlets and I'll give you feedbacks ASAP.
