### ISSUE TITLE
Implement flags "categories", "discussion", "ratings", "tags" and "relatedAssets" on "asset" element

### ISSUE THREAD

**Issue by slemarchand** [yasuflatland-lf/damascus#13]
It can be valuable to implement the flags **`categories`**, **`discussion`**, **`ratings`**, **`tags`** and **`relatedAssets`** on asset element, for file `base.json`.

@yasuflatland-lf If you accept help for this task, I can implement the features and send you a pull request.

**Comment by yasuflatland-lf** [comment]
@slemarchand , sure, please go ahead. Thank you for this contribution!

**Comment by yasuflatland-lf** [comment]
@slemarchand , thank you for this contribution!
