### ISSUE TITLE
Add Liferay minimal required versions to the readme file

### ISSUE THREAD

**Issue by slemarchand** [yasuflatland-lf/damascus#14]
Since the last release, it seems that the minimal required versions of Liferay for generated code was higher than previously (now it seems to be Liferay 7.0 CE GA4 and Liferay DXP SP3).

It will be very valuable to add the minimal required versions to the readme file.

**Comment by yasuflatland-lf** [comment]
Added. e146c1714f0498a18ef689400fc343051cb0c9f1
