### ISSUE TITLE
 Language properties support

### ISSUE THREAD

**Issue by yasuflatland-lf** [yasuflatland-lf/damascus#41]

**Comment by tiurlumbangaol** [comment]
hi,
i assume with commit https://github.com/yasuflatland-lf/damascus/commit/4bcb177e5d4eb8c48dac8807e76f03ec1cd559de that you could close this issue?

**Comment by yasuflatland-lf** [comment]
@tiurlumbangaol Yeah, you are right, let me close now. Thank you for the heads up!
