### ISSUE TITLE
Remove duplicate templates in src/test/resources/templates ?

### ISSUE THREAD

**Issue by slemarchand** [yasuflatland-lf/damascus#6]
The templates in `src/test/resources/templates` directory (duplicated from `src/main/resources/templates`) seems not to be used.

Should we remove this directory?

**Comment by yasuflatland-lf** [comment]
Hi @slemarchand 

Yeah, right, all codes are same so far. My initial intention was if some tests needed test dedicated code, (say variations of base.json for different test cases, e.g ) separating them would be beneficial, which is the current implementation.

So, I basically agree with your idea, but I'm still bit concerned. What's your opinion about that part?

**Comment by slemarchand** [comment]
Hi @yasuflatland-lf,

Basically, the main disavantage of keeping duplicate templates is that it forces us to synchronize the templates after each modification.

From my point of view, it's better to remove identical templates from the `src/test/resources/templates` directory, and to place in this directory only the modified templates for the need of a test case.
