### ISSUE TITLE
Unable To Use The Command (damascus -create)

### ISSUE THREAD

**Issue by ghost** [yasuflatland-lf/damascus#61]
![damascus-issues](https://user-images.githubusercontent.com/34816258/50083601-50d43300-021a-11e9-9bed-82d324c71c4e.gif)
Please look for more detail in the gif attached.

**Comment by ghost** [comment]
Also Provide details with respect to whether its support for Liferay 7.1

**Comment by yasuflatland-lf** [comment]
@rahulholalkere Released 1.0.17 (f1b8064ec6dbb912820df26ad620088aed2b2d35). It should work now.
