### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by tiurlumbangaol** [yasuflatland-lf/damascus#65]
Create "Advanced Search" Functionality.

We already created this for 7.0 version, we need to customise so it support 7.1 version.

**Comment by yasuflatland-lf** [comment]
@tiurlumbangaol , can share your code by PR so that I can figure out?

**Comment by tiurlumbangaol** [comment]
ok, tomorrow will do it. but please bare with us, it is our first time using github for this kind of collaboration.

**Comment by tiurlumbangaol** [comment]
Hi,

We created pull request for this, please check : 
https://github.com/yasuflatland-lf/damascus/pull/70
