### ISSUE TITLE
generated *-web project has a gradle folder which is unnecessary

### ISSUE THREAD

**Issue by AndyWu2015** [yasuflatland-lf/damascus#7]
see here
![gradlefolder](https://user-images.githubusercontent.com/12250744/27385152-3069a918-56c4-11e7-8f2b-b7704f85b98d.png)

**Comment by yasuflatland-lf** [comment]
Hey @AndyWu2015 , thank you for pointing this out. I need to figure out how to deal with unit testing, but I'll work on this with https://github.com/yasuflatland-lf/damascus/issues/1.

**Comment by yasuflatland-lf** [comment]
fixed in cd1656853e75e5648baf60a1d2d887b96fd1b2bd
