### ISSUE TITLE
Trying to create build relationship sample app i.e. todo and getting build failed.

### ISSUE THREAD

**Issue by himanshubhandari5** [yasuflatland-lf/damascus#74]
Hi, Thanks for this plugin, it is simply awesome. I am exploring it and trying to implement it in a sample project, and facing issue from last 3 days. I am able to generate services for service plugin but while building it I am getting following error logs:

C:\LR7\work\lrwrk\modules\todo\employee-service>blade gw build
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details

> Task :modules:todo:employee-service:jar FAILED
warning: No sub JAR or directory lib/guava.jar
warning: No sub JAR or directory lib/error_prone_annotations.jar
warning: No sub JAR or directory lib/commons-digester.jar
warning: No sub JAR or directory lib/commons-validator.jar
warning: No sub JAR or directory lib/commons-io.jar
warning: No sub JAR or directory lib/commons-lang3.jar
error  : Input file does not exist: guava-[0-9]*.jar
error  : Input file does not exist: error_prone_annotations-[0-9]*.jar
error  : Input file does not exist: commons-digester-[0-9]*.jar
error  : Input file does not exist: commons-validator-[0-9]*.jar
error  : Input file does not exist: commons-io-[0-9]*.jar
error  : Input file does not exist: commons-lang[0-9]*.jar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':modules:todo:employee-service:jar'.
> Bundle com.liferay.sb.employee.service-1.0.0.jar has errors

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 21s
5 actionable tasks: 1 executed, 4 up-to-date
----------------------------------------------------------------------------------------------------------

Please let me know what is wrong with what I am doing. I am using the same base.json from https://yasuflatland-lf.github.io/damascus-doc/docs/samples/sample1.html on windows 10

Thank you!

**Comment by yasuflatland-lf** [comment]
Hi @hdbhandari , Thank you for using Damascus and contact this time. Let me clarify your environment here before going into the investigation. 

* What version of Liferay are you targeting? (7.0, 7.1 or 7.2?)
* What version of Damascus are you using? (Run `damascus` and it'll show the version on the top.). Please use the latest version and templates. (if you delete `${home_dir}/.damascus`, Damascus will generate the latest template)
* Please make sure you are using the correct Liferay Workspace. For example, if you are using 7.1, then you need to create the Liferay Workspace with `blade init -v 7.1`
* Did you choose the correct template for Damascus? For example, if you want to generate 7.1 CRUD scaffolding, After generated **Liferay Workspace for 7.1** and go to `${liferay_workspace_root}/modules` and run `damascus init -c Todo -p com.liferay.sb.test -v 7.1` for example. 

Please let me know if you still get errors.

**Comment by himanshubhandari5** [comment]
Hi @yasuflatland-lf , thank you for replying back. I should have provided these details in first shot, sorry! Well here they are:

- I am targeting version 7.1 CE GA4

- C:\LR7\work\lrwrk>damascus
Version : 20190429

- Yes, I have created fresh workspace.  Just to confirm here is the content from .blade.properties, I think it will reflect correct version of Liferay Workspace.
#Fri Jun 28 17:05:00 IST 2019
liferay.version.default=7.1
profile.name=gradle

- Yes I have used the same command. However I have replaced base.json completely with the URL https://yasuflatland-lf.github.io/damascus-doc/docs/samples/sample1.html 

Please let me know if should provide any more information.

**Comment by yasuflatland-lf** [comment]
@hdbhandari This occurs on Mac as well. It's the cause of the generated code. Will fix this.

**Comment by yasuflatland-lf** [comment]
@hdbhandari Please try Ver 1.0.23

**Comment by himanshubhandari5** [comment]
Thank you! Error is gone now.

**Comment by yasuflatland-lf** [comment]
@hdbhandari Thank you for your update! Enjoy coding!
