### ISSUE TITLE
7.2 Template update

### ISSUE THREAD

**Issue by yasuflatland-lf** [yasuflatland-lf/damascus#75]
Update template to 7.2

**Comment by lionlin0727** [comment]
When will the 7.2 templates be released?

**Comment by yasuflatland-lf** [comment]
@lionlin0727  See [this project](https://github.com/yasuflatland-lf/damascus/projects/4) for the progress.

**Comment by lionlin0727** [comment]
@yasuflatland-lf 
thanks for your reply.

**Comment by tiurlumbangaol** [comment]
hi @yasuflatland-lf any possibilities for us to access the 7.2 support? maybe put it on "develop" branch?

**Comment by yasuflatland-lf** [comment]
Implemented in 1429c1926c702d8587805b2b6cc18fc2eff4e53d

**Comment by yasuflatland-lf** [comment]
@tiurlumbangaol , it's been released in 1.1.1, master branch. let me create a release.
