### ISSUE TITLE
there is a problem in management-toolbar

### ISSUE THREAD

**Issue by lionlin0727** [yasuflatland-lf/damascus#78]
I can't search anything with search input!
And The combination search function has disappeared which worked good in Dxp7.1!

**Comment by yasuflatland-lf** [comment]
Hi @lionlin0727 

> I can't search anything with search input!

Can you share your `base.json`? Did you search on the management bar or in the search field right top on the user top page?

> The combination search function has disappeared which worked good in Dxp7.1!

This is intentional. the reasons are:
- The user interface code has been drastically changed since 7.0. so it would take longer to merge the code
- The advanced search relies on the query to a database, which could be a performance issue on production. 
- Most of the use cases that I've experienced, needed a simple minimal scaffolding base. So I also got rid of Activities, ratings, and comments as they've not been often used.

**Comment by tiurlumbangaol** [comment]
hi @yasuflatland-lf on our projects, it is common to use advanced search, if you allow we can upgrade the advanced search so it will be there on 7.1

If you are ok, i will create issue for this, and our team will the one who work on it.

**Comment by yasuflatland-lf** [comment]
@tiurlumbangaol, Thank you for your offering, really appreciate it. I'll create a ticket with a brief instruction on how I want it to be implemented.

**Comment by lionlin0727** [comment]
> Hi @lionlin0727
> 
> > I can't search anything with search input!
> 
> Can you share your `base.json`? Did you search on the management bar or in the search field right top on the user top page?

⇒Thanks for your reply.My base.json is below.I just use the search field on clay:management-toolbar
and get nothing .
<clay:management-toolbar
	actionDropdownItems="<%= todoManagementToolbarDisplayContext.getActionDropdownItems() %>"
	clearResultsURL="<%= todoManagementToolbarDisplayContext.getSearchActionURL() %>"
	componentId="todoManagementToolbar"
	creationMenu="<%= todoManagementToolbarDisplayContext.getCreationMenu() %>"
	disabled="<%= todoManagementToolbarDisplayContext.isDisabled() %>"
	filterDropdownItems="<%= todoManagementToolbarDisplayContext.getFilterDropdownItems() %>"
	itemsTotal="<%= todoManagementToolbarDisplayContext.getItemsTotal() %>"
	searchActionURL="<%= todoManagementToolbarDisplayContext.getSearchActionURL() %>"
	searchContainerId="todo"
	searchFormName="fm"
	showSearch="true"
	sortingOrder="<%= todoManagementToolbarDisplayContext.getOrderByType() %>"
	sortingURL="<%= todoManagementToolbarDisplayContext.getSortingURL() %>"
/>

{
  "projectName": "Todo",
  "packageName" : "com.liferay.sb.test",
  "liferayVersion": "7.2",
  "applications": [
    {
      "model"       : "Todo",
      "title"       : "Todo Test",
      "web"         : "true",
      "asset": {
        "assetTitleFieldName": "todoTitleName",
        "assetSummaryFieldName": "todoSummaryName",
        "categories": "false",
        "discussion": "false",
        "ratings": "false",
        "tags": "false",
        "relatedAssets": "false",
        "fullContentFieldName": "todofullContent",
        "workflow": "true",
        "generateActivity": "true",
        "trash":"true",
        "advancedSearch": "true",
        "exportExcel": "true"
      },
      "fieldsName" : "Todos",
      "fields": [
        {
          "type": "com.liferay.damascus.cli.json.fields.Long",
          "primary":true,
          "name": "todoId",
          "title": "Todo Id",
          "showFieldInView": "false",
          "required": "true"
        },
        {
          "type": "com.liferay.damascus.cli.json.fields.Varchar",
          "name": "title",
          "title": "Title",
          "length": "80",
          "showFieldInView": "true",
          "required": "true"
        },
        {
          "type": "com.liferay.damascus.cli.json.fields.Boolean",
          "name": "todoBooleanStat",
          "title": "Status"
        },
        {
          "type": "com.liferay.damascus.cli.json.fields.DateTime",
          "name": "todoDateTime",
          "title": "Reserve Date"
        },
        {
          "type": "com.liferay.damascus.cli.json.fields.Integer",
          "name": "todoInteger",
          "title": "Todo Cost"
        },
        {
          "type": "com.liferay.damascus.cli.json.fields.RichText",
          "name": "todoRichText",
          "title": "Todo Comment"
        },
        {
          "type": "com.liferay.damascus.cli.json.fields.Text",
          "name": "todoText",
          "title": "Todo Others"
        }
      ],
      "customValue" : {
        "your_own_id" : "your_custom_value_for_template_here"
      },
      "replacements" : {
        "original_string_to_be_replaced" : "replacement_string"
      }
    }
  ]
}


> > The combination search function has disappeared which worked good in Dxp7.1!
> 
> This is intentional. the reasons are:
> 
> * The user interface code has been drastically changed since 7.0. so it would take longer to merge the code
> * The advanced search relies on the query to a database, which could be a performance issue on production.
> * Most of the use cases that I've experienced, needed a simple minimal scaffolding base. So I also got rid of Activities, ratings, and comments as they've not been often used.


⇒thanks for your explaination! we would like to use the advanced search function.
   we will merge the source of Dxp7.1 version to Dxp7.2 version.
