### ISSUE TITLE
Advanced Search migration for 7.2 template

### ISSUE THREAD

**Issue by yasuflatland-lf** [yasuflatland-lf/damascus#79]
Upgrade Advanced Search for 7.2. 

@tiurlumbangaol  Regarding code, could you implement it as below?

- Place search parameter related code in *ViewHelper.java (They were used be coded in `view.jsp`)
- Enable / Disable `advancedSearch` switch in `base.json`
- Regarding advanced search field, please place them in a panel such as below. Also please comply Clay 2.0 for the form elements, such as Text Field, Dropdown, etc.
```
<aui:a href="#inputOptions" cssClass="collapse-icon collapsed icon-angle-down" title="Option" aria-expanded="false" data-toggle="collapse" >&nbsp;&nbsp;option</aui:a>
<div class="collapsed collapse" id="inputOptions" aria-expanded="false" >
[ Advanced Search components come here]
・
・
・
</div>
```

**Comment by tiurlumbangaol** [comment]
hi @yasuflatland-lf please give us time, maybe on beginning of Feb 2020, we could start the development...

**Comment by yasuflatland-lf** [comment]
Old version will leave as it is. Close this.
