### ISSUE TITLE
Import Liferay Module Project: Location is not recognized

### ISSUE THREAD

**Issue by icarrara** [yasuflatland-lf/damascus#80]
At first, many congratulations for the great work.

I'll consider to use Damascus so I'm starting some tests related to our use cases.

I undertand that this is not an Issue and the I'm not in the right place but I'll try to post the below question: In Liferay Developer Studio pointing to the 'modules' folder  I tried to Import ---> Liferay Module Projects(s) but picking the 'todo' folder generated by Damascus I get the "Location is not recognized as a valid projecy type" error.

Please could you help me ?

Moreover, are you planning some form of Support forum or other form of Support service?

Thank you in advance.
Ivano C.

**Comment by icarrara** [comment]
Update: If you create a new module in the 'modules' folder, Liferay Developer Studio import other modules not yet in the workspace autonomously. This close the issue for me.

Moreover, are you planning some form of Support forum or other form of Support service?

Thank you in advance.
Ivano C.

**Comment by yasuflatland-lf** [comment]
Hi @icarrara , thank you for being interested in Damascus! Answering your question quickly, in case you create a project by Damascus, you may want to run "Refresh" and "Refresh Gradle Project" in the Liferay Developer Studio (LDS). What I tried and confirmed are the following steps. 

I hope it works for you.

1. Create a new folder `ldrtmp`
2. Open up LDS and point the workplace to the `ldrtmp` folder
3. Under the `ldrtmp` folder, create `ws` folder and navigate there
4. Run “blade init -v 7.2” and create Liferay 7.2 workspace.
5. Go to modules folder, and run `damascus init -c Todo -p com.liferay.sb.test -v 7.2`
6. And go to todo folder and run `damascus create`
7. In LDS menu, File -> import and import the `ws` folder as `Liferay Workspace Project`. Select Workspace Location (the `ws` folder. Leave build type as it is, `gradle-liferay-workspace`, assuming you are using gradle.
8. In the Project Explorer, right-click on `ws`, imported Liferay Workspace and in the context menu, select `Refresh`. It may take a while to refresh the project
9. You may be able to see the `Todo` bundles are recognized as gradle projects. In case you still see general folder icons, not gradle project folder icon, select `ws` in the Project Explorer panel and do right-click, then in the context menu, select `Gradle -> Refresh Gradle Project`, then you’ll be able to see the projects properly recognized as Gradle projects

**Comment by yasuflatland-lf** [comment]
Hi, @icarrara , I created Gitter account for the communication.
https://gitter.im/liferay-damascus/community#

Will add a link as a badge in README.md when I release next time.

**Comment by icarrara** [comment]
Hi @yasuflatland-lf , great !

I just joined damascus/community.

Thank you !

**Comment by icarrara** [comment]
Ok, it worked.

Thank you @yasuflatland-lf  !

**Comment by icarrara** [comment]
The import worked for the first project "Todo".
Then I tried to import the second project "Employee" and again I'm not able to import in the same liferay workspace:
![immagine](https://user-images.githubusercontent.com/2285400/70166395-f51de680-16c4-11ea-8e38-74f9a374e660.png)

When I try to import the "emplyee" folder I get the below error:
![immagine](https://user-images.githubusercontent.com/2285400/70166687-8beaa300-16c5-11ea-977b-7a4f204350d3.png)

**Comment by icarrara** [comment]
I found the workaround: Every time a create a new Damascus project, I delete the liferay workspace from Liferay Developer Studio and then reimport it.

**Comment by yasuflatland-lf** [comment]
@icarrara , you may just need to place the employee project and try the way that [I introduced above](https://github.com/yasuflatland-lf/damascus/issues/80#issuecomment-557279883). LDS would recognize the project properly.

**Comment by icarrara** [comment]
For sure it is my fault but what you introduced above it is ok for the first module, in my case Todo module. I imported it successifully following your directives.

My problem is to import the second (Employee) and other modules after the first Todo module.

I tried to import Employee module as a Liferay Module Project what it fails as you can see in the previous scree shot.

My workaround is to delete the whole liferay workspace and then reimport again after I generated new modules using Damascus.

**Comment by yasuflatland-lf** [comment]
@icarrara Got it, thank you for your clarification. Let me try to import the second module in the Liferay Workspace in Liferay Developer Studio.

**Comment by yasuflatland-lf** [comment]
@icarrara, it worked for me, Liferay Developer Studio(3.6.2) loaded 2 projects (employee, a sample of 2 models relations and todo, the initial sample that Damascus creates) properly. The steps are below:
1. Create a workspace for Liferay Developer Studio(LDS), say `${home}/ldstest`
1. Create `${home}/ldstest/ws` directory and go to the directory, then run `blade init -v 7.2`
1. Back to LDS, Import the Liferay Workspace just created, `File > import > Liferay Workspace`
1. Go to `modules` and run `damascus init -c Todo -p com.liferay.sb.test -v 7.2` and then go to `todo` directory and run `damascus create`
1. On LDS, right-click on the `ws` root folder and run `refresh` and `gradle > Refresh Gradle Project`. You'll see the `todo` project recognized a gradle project.
1. Go back to the console and run `damascus init -c Employee -p com.liferay.sb -v 7.2` and copy and past the [sample](https://yasuflatland-lf.github.io/damascus-doc/docs/samples/sample1.html) in `base.json` and run `damascus create`
1. On LDS, right-click on the `ws` root folder and run `refresh` and `gradle > Refresh Gradle Project`. You'll see the `employee` project recognized a gradle project without errors.

I basically didn't use LDS for the loading module... If you consider this is a bug, please go ahead to report this on [our official bug tracker for IDE](https://issues.liferay.com/projects/IDE/summary)

**Comment by icarrara** [comment]
Dear @yasuflatland-lf, thank you very much for your help.

I'm a bit confused and frustrated because solving one thing then I get new issue.
The gradle > Refresh Gradle Project works but now all references to Todo* and Employee* are in error.

I changed to "distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-bin.zip" in the "gradle\wrapper\gradle-wrapper.properties" file because with the original "4.10.2" version the import fails.

Here is the LDS status after the import of Liferat workspace:
![immagine](https://user-images.githubusercontent.com/2285400/70344777-cdf91d80-185a-11ea-9482-cd11cfe0aba7.png)

The errors are caused by references to Todo and Employee models:
![immagine](https://user-images.githubusercontent.com/2285400/70344880-04cf3380-185b-11ea-9870-50d29f1579d8.png)
But build.gradle has references to -service and -api modules:
`// 
//   //
//  //
apply plugin: 'java'
apply plugin: 'groovy'
apply plugin: 'idea'
apply plugin: 'eclipse'

sourceCompatibility = 1.8
targetCompatibility = 1.8

//Need for Windows
def defaultEncoding = 'UTF-8'

dependencies {
	compile group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.5.0"
	compile group: "org.apache.poi", name: "poi", version: "4.0.1"
	compile group: "org.apache.poi", name: "poi-ooxml", version: "4.0.1"
	compile group: "org.apache.poi", name: "poi-ooxml-schemas", version: "4.0.1"

	compileOnly group: "com.liferay", name: "com.liferay.application.list.api", version: "4.0.+"
	compileOnly group: "com.liferay", name: "com.liferay.asset.api", version: "2.1.+"
	compileOnly group: "com.liferay", name: "com.liferay.asset.display.page.api", version: "5.1.0"
	compileOnly group: "com.liferay", name: "com.liferay.asset.display.page.item.selector.api", version: "2.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.asset.info.display.api", version: "2.1.0"
	compileOnly group: "com.liferay", name: "com.liferay.asset.taglib", version: "4.0.+"
	compileOnly group: "com.liferay", name: "com.liferay.comment.taglib", version: "2.0.+"
	compileOnly group: "com.liferay", name: "com.liferay.frontend.taglib", version: "4.0.+"
	compileOnly group: "com.liferay", name: "com.liferay.frontend.taglib.clay", version: "2.1.+"
	compileOnly group: "com.liferay", name: "com.liferay.frontend.taglib.soy", version: "3.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.frontend.taglib.util", version: "2.0.+"
	compileOnly group: "com.liferay", name: "com.liferay.info.api", version: "4.0.+"
	compileOnly group: "com.liferay", name: "com.liferay.item.selector.api", version: "4.0.+"
	compileOnly group: "com.liferay", name: "com.liferay.item.selector.criteria.api", version: "4.0.+"
	compileOnly group: "com.liferay", name: "com.liferay.item.selector.taglib", version: "3.0.+"
	compileOnly group: "com.liferay", name: "com.liferay.petra.reflect", version: "3.0.+"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "4.13.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.util.taglib", version: "4.1.0"
	compileOnly group: "javax.portlet", name: "portlet-api", version: "3.0.1"
	compileOnly group: "javax.servlet.jsp", name: "javax.servlet.jsp-api", version: "2.3.1"
	compileOnly group: "jstl", name: "jstl", version: "1.2"
	compileOnly group: "org.apache.felix", name: "org.apache.felix.http.servlet-api", version: "1.1.2"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.3.0"
	compileOnly project(":modules:employee:employee-api")
	compileOnly project(":modules:employee:employee-service")
}

So I'm in a bad moment.

Please could you help me some more ?
Ivano C.`

**Comment by yasuflatland-lf** [comment]
@icarrara You are basically not necessary to modify any code or Gradle versions that `blade gw` command use for compile, deploy and load the code in LDS. Let me ask some questions.

- What version of LDS are you using?
- Is the Liferay Workspace targeting 7.2?
- What version of `blade` are you using?  (you can check the version with `blade version` command)
- What version of JDK your LDS is targeting to? (Damascus is only Java 8 compatible for now)
- What's your JDK version installed on your machine? 
- Is your environment behind a proxy? (Are you using your machine in the network behind proxy?)

**Comment by icarrara** [comment]
Dear @yasuflatland-lf , below the environment:

    What version of LDS are you using? 3.7.1.201910160309-ga2
    Is the Liferay Workspace targeting 7.2? 7.2.0
    What version of blade are you using? 3.8.0.201909200317
    What version of JDK your LDS is targeting to? 1.8.0_161
    What's your JDK version installed on your machine? 1.8.0_161
    Is your environment behind a proxy? No. It download every thing its needs

I'll try to restart from scratch ...

**Comment by yasuflatland-lf** [comment]
@icarrara the environment looks ok to me. It looks like the issue of LDS side that it doesn't recognize libraries paths. What you may be able to do is
- Use IntelliJ CE and IntelliJ plugin that Liferay provides (IntelliJ works without the plugin, but need to create module projects from the command line)
- Use general Eclipse and load the module project, (say todo) as Gradle modules. 
- At each project root, say `todo` and run `blade gw eclipse`, which will generate Eclipse project files under each bundle, then restart LDS. This way may help LDS recognize the Java build paths for each bundle.

**Comment by icarrara** [comment]
Dear @yasuflatland-lf ,

I restarted from scratch and finally the environment is working and it imports Damascus project without problems.

The actual environment as below:

- What version of LDS are you using? 3.7.1.201910160309-ga2
- Is the Liferay Workspace targeting 7.2? 7.2.0
- What version of blade are you using? 3.8.0.201909200317
- What version of JDK your LDS is targeting to? 1.8.0_161
- What's your JDK version installed on your machine? 1.8.0_161
- Is your environment behind a proxy? No.
- **damascus.build.number=V1.1.2TS20191208060334**

Thank you for your support.
You can close the issue if you wish.

**Comment by yasuflatland-lf** [comment]
@icarrara ok!
