### ISSUE TITLE
Relation Sample fails to display Position in a pull-down list in Employee edit page

### ISSUE THREAD

**Issue by icarrara** [yasuflatland-lf/damascus#83]
Deployed the Relation Sample application but it fails to display Position in a pull-down list in Employee edit page:

![immagine](https://user-images.githubusercontent.com/2285400/69355901-e6760f00-0c82-11ea-9f5d-892c855e3efc.png)

**Comment by yasuflatland-lf** [comment]
@icarrara should be fixed in 1.1.2

**Comment by icarrara** [comment]
@yasuflatland-lf , thank you very much for your efforts.
