### ISSUE TITLE
Installation of lombok library fails

### ISSUE THREAD

**Issue by icarrara** [yasuflatland-lf/damascus#85]
- Downloaded lombok from https://projectlombok.org/download
- Double clicked lombok.jar and selected the directory where I installed Liferay Developer Studio. There is not eclipse.exe but eclipse**c**.exe
- lombok installation fails

**Comment by yasuflatland-lf** [comment]
@icarrara could you explain to me more details? Are you trying to build Damascus on your own? Or simply trying to use Lombok for generated modules in the Liferay Developer Studio?

**Comment by icarrara** [comment]
@yasuflatland-lf I wish to use Damascus to generate CRUD module skeleton for Liferay Portal 7.2.1.

I read in the README.md in the IDE settings section that I need to install lombok so I tried.

But when I double click lombok.jar and select the directory where I installed Liferay Developer Studio, there is not eclipse.exe but eclipsec.exe so lombok installation fails

**Comment by yasuflatland-lf** [comment]
@icarrara Ok, understood. You are not necessarily to install Lombok unless either you build Damascus tool itself by yourself or want to use Lombok in your modules. The example means plain Eclipse IDE, doesn't mean Liferay Developer Studio. I've not tried to use Lombok with LDS myself.

**Comment by icarrara** [comment]
Ok, thank you !
