### ISSUE TITLE
add new field in module created (change current base.json)

### ISSUE THREAD

**Issue by mkhhatampoor** [yasuflatland-lf/damascus#87]
hi
after module created by damascus, maybe needs a field add to an entity (or maybe  some of methods or UI that autogenerated, required changes manually and then required add a field to an entity or other changes in base.json).
what is solution for this scenario?

**Comment by yasuflatland-lf** [comment]
Damascus is designed to generate Scaffolds once. It is not designed to regenerate code according to the changes of fields later on. In that case, modify `base.json`, clean up generated bundles and run `damascus create` again.
