### ISSUE TITLE
Implement *generateActivity* flag on *asset* element (base.json file)

### ISSUE THREAD

**Issue by slemarchand** [yasuflatland-lf/damascus#9]
It can be valuable to implement the **`generateActivity`** flag on **`asset`** element, for file `base.json`.

@yasuflatland-lf If you accept help for this task, I can implement the feature and send you a pull request.

**Comment by yasuflatland-lf** [comment]
@slemarchand, sure, but Activities and displaying records on Asset Publisher currently doesn't work properly. Let me fix them first. In terms of Activities, I've already fixed and committed in the reference implementation, [SampleSB](https://github.com/yasuflatland-lf/SampleSB) and working on fixing Asset Publisher issue now.  Once I'm done with fixing them, will merge them into the templates of Damascus.

**Comment by yasuflatland-lf** [comment]
Hi @slemarchand, I just fixed Activities and Asset renderer issues, so please go ahead implement the flag for activities.
