### ISSUE TITLE
how disable workflow or asset in base.json?

### ISSUE THREAD

**Issue by mkhhatampoor** [yasuflatland-lf/damascus#90]
hi
i config base.json for my portlet that not require asset and workflow. if i set  "workflow": "false", when deploy my module, error occur: (some of method related to workflow not created)
modules/todo/todo-service/src/main/java/com/liferay/sb/test/service/impl/TodoLocalServiceImpl.java
cannot find symbol method countByG_S(long,int[])
cannot find symbol method countByU_S(long,int[])
cannot find symbol method countByG_U_S(long,long,int[])
cannot find symbol method findByG_S(long,int[])
cannot find symbol method findByG_S(long,int[],int,int,OrderByComparator<Todo>)
cannot find symbol method findByU_S(long,int[])
cannot find symbol method findByU_S(long,int[],int,int,OrderByComparator<Todo>)
cannot find symbol method findByG_U_S(long,long,int[]) 
.......

when i remove asset block in base.json for portlet that not require asset, error occur.

do we force for choose asset and workflow?

**Comment by icarrara** [comment]
@mkhhatampoor yes, you have to force for choose asset and workflow.

Until now `"workflow": "true"` is the only value supported, since 'false' is not implemented.

**Comment by yasuflatland-lf** [comment]
@icarrara Thank you for your comment!
