### ISSUE TITLE
tabular entities instead create portlets in one module with multiple entity

### ISSUE THREAD

**Issue by mkhhatampoor** [yasuflatland-lf/damascus#91]
hi 
now for every entity that exist in base.json, one portlet will be created. for my sample that have 15 entities, this is not useful. my portlet in liferay 6.1 is tabular and for an entity have one tab in one portlet.
why do you create portlet for every entity? and do you doing that(tabular portlet)? and what is your idea that i perform that?
tanks

**Comment by yasuflatland-lf** [comment]
Hi @mkhhatampoor thank you for the comment. The current design is aiming for avoiding the complexity of templates. To accomplish your requirements, multiple entities need to refer to the same generated file, which could be a cause of complexity. The current template engine handles each entity in each loop. 

So this is intentionally designed that way for now. If there is a better implementation of the template engine regarding this, any ideas will be appreciated.
