### ISSUE TITLE
View and Update actions fails in portlet deployed in Content Page

### ISSUE THREAD

**Issue by icarrara** [yasuflatland-lf/damascus#92]
In **Content** Page, View and Update actions fails to works.
Simply no action follows after clicks View and Update actions.

Using damascus.build.number=V1.1.3TS20191209041928

Create a **Content** Page and deploy Todo sample portlet, then:
- Create some records.
- View Action: No
- Update Action: No
- Permisison: Yes
- Delete: Yes
- Move to Trash: Yes

Create a **Widget** Page and deploy Todo sample portlet, then:
- Create some records.
- View Action: Yes
- Update Action: Yes
- Permisison: Yes
- Delete: Yes
- Move to Trash: Yes

Tested in:
- Liferay Community Edition Portal 7.2.0 CE GA1
- Liferay Community Edition Portal 7.2.1 CE GA2

**Comment by icarrara** [comment]
@yasuflatland-lf verified that the link issues on Content Pages were a Liferay's bug. Until it's resolved, the friendly URL mapping file(routes.xml) is commented out in Damascus v.1.1.5. 

I confirm that in v.1.1.5 the friendly URL mapping file(routes.xml) commented out is a working solution.  View and Update actions works in Liferay 7.2.0 and 7.2.1.

**Comment by yasuflatland-lf** [comment]
@icarrara Thank you for your confirmation! I really appreciate your help with this issue!
